version: "3"

services:
 carousel:
  build:
   context: .
  ports:
   - 3001:3001
  environment:
   - CONNECTIONSTRING=mongodb://mongo:27017/listings
  volumes:
   - ./:/code
 mongo:
  image: mongo:4.4.1
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:

